name: Psalm

on:
  pull_request:
  push:

jobs:
  psalm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer
          coverage: none
          extensions: dom, simplexml

      - name: Validate composer.json
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Psalm
        run: composer run psalm
